# Node.js 이미지를 기반으로 사용
FROM node:16-slim

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 package-lock.json 복사
COPY web/package*.json ./

# 필요한 패키지 설치
RUN npm install

# 소스 코드 복사
COPY web/src ./src
COPY web/public ./public

# 포트 설정
EXPOSE 3000

# 애플리케이션 실행
CMD ["node", "src/server.js"] 